image: registry.gitlab.com/kaamit/certiapp/certiapp-api:test


cache:
  paths:
    - vendor/
    - config/jwt
    - var/.phpcs-cache


before_script:
  - composer install
  # generate SSH keys
  - mkdir -p config/jwt
  - openssl genrsa -out config/jwt/private.pem -aes256 -passout pass:qwerty 4096
  - openssl rsa -pubout -in config/jwt/private.pem -passin pass:qwerty -out config/jwt/public.pem


services:
  - mysql:5.7


variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: certiapp_test
  MYSQL_ROOT_PASSWORD: root
  DATABASE_URL: 'mysql://root:root@mysql:3306/certiapp_test'
  SYMFONY_DEPRECATIONS_HELPER: 'disabled'

test:
  variables:
    APP_ENV: test
    APP_DEBUG: 0
  only:
    - merge_requests
  script:
    - php bin/console doctrine:schema:create
    - php bin/console doctrine:fixtures:load
    - vendor/bin/codecept run api --steps


deploy_prod:
  when: manual
  stage: deploy
  only:
    - master
  environment: Production
  script:
    - echo $SERVICE_ACCOUNT
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet app deploy prod.yaml --project $PROJECT_ID


deploy_staging:
  when: manual
  stage: deploy
  only:
    - master
  environment: Staging
  script:
    - echo $SERVICE_ACCOUNT
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet app deploy dev.yaml --project $PROJECT_ID


#after_script:
#  - rm /tmp/$CI_PIPELINE_ID.json
