runtime: php
env: flex
service: api-dev

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10

runtime_config:
  document_root: public
  front_controller_file: index.php
  skip_lockdown_document_root: true
  enable_stackdriver_integration: false

env_variables:
  APP_ENV: prod
  APP_SECRET: 56hjg7k56jg47654jg7456g7u45gy67ig
  GOOGLE_CLOUD_PROJECT: certiapp
  DATABASE_URL: 'mysql://certiapp:iPj!myVCkW6@localhost?unix_socket=/cloudsql/certiapp:europe-west1:certiapp-develop;dbname=certiapp_dev'
  JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
  JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'
  JWT_PASSPHRASE: qwerty
  JWT_TOKENTTL: 3600
  MAILER_URL: 'null://localhost'
  CORS_ALLOW_ORIGIN: '^https?://.*?$'
  NELMIO_HOST: 'api-dev-dot-certiapp.appspot.com'

beta_settings:
  cloud_sql_instances: 'certiapp:europe-west1:certiapp-develop'
