runtime: php
env: flex
service: muchfit-api

resources:
  cpu: .5
  memory_gb: 1
  disk_size_gb: 10

runtime_config:
  document_root: public
  front_controller_file: index.php
  skip_lockdown_document_root: true

env_variables:
  APP_ENV: prod
  GOOGLE_CLOUD_PROJECT: muchfit
  APP_SECRET: 56hjg7k56jg47654jg7456g7u45gy67ig
  DATABASE_URL: mysql://muchfituser:muchfituser01@localhost?unix_socket=/cloudsql/muchfit:europe-west1:muchfitmysql;dbname=much_fit_dev
  JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
  JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'
  JWT_PASSPHRASE: qwerty
  JWT_TOKENTTL: 3600
  CORS_ALLOW_ORIGIN: '*'


beta_settings:
  cloud_sql_instances: 'muchfit:europe-west1:muchfitmysql'
