parameters:
    onurb_yuml.extension: png
    onurb_yuml.style: plain
    onurb_yuml.scale: small
    onurb_yuml.direction: TB
    onurb_yuml.show_fields_description: false
    onurb_yuml.colors:
        App\Entity\User: yellow
        App\Entity\Role: yellow
        App\Entity\TestUsuario: lawngreen
        App\Entity\TestUsuarioDieta: lawngreen
        #RUTINA
        App\Entity\Rutina: deepskyblue
        App\Entity\Dia:  deepskyblue
        App\Entity\DiaEjercicio:  deepskyblue
        App\Entity\Ejercicio:  deepskyblue
        #DIETA
        App\Entity\Dieta: violet
        App\Entity\DiaDieta:  violet
        App\Entity\Meal:  violet



