parameters:
    onurb_yuml.extension: svg
    onurb_yuml.style: plain
    onurb_yuml.scale: small
    onurb_yuml.direction: TB
    onurb_yuml.show_fields_description: false
    onurb_yuml.colors:

#        plantillas
        App\Entity\PlantillaChecklist: brown
        App\Entity\PlantillaMuestra: brown
        App\Entity\PlantillaRequerimiento: brown

#        auth
        Gesdinet\JWTRefreshTokenBundle\Entity\AbstractRefreshToken: yellow
        Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken: yellow
        App\Entity\User: yellow
        App\Entity\Role: yellow

#        core
        App\Entity\Empresa: orange
        App\Entity\App: orange
        App\Entity\GrupoAlcance: orange
        App\Entity\Alcance: orange
        App\Entity\EmpresaAlcance: orange
        App\Entity\Event: orange
        App\Entity\Flujo: orange
        App\Entity\TipoNoconformidad: orange
        App\Entity\Dropdown: orange
